chore: Dump logs on failure in cleanup hook
Since the shell `-e` option is enabled, the condition for dumping the
logs is never reached. This commit cleans this up and puts it in the
cleanup hook. The SIGINT and SIGTERM does not trigger cleanup to allow
debugging of the running composition.

Signed-off-by: Alf-Rune Siqveland <alf.rune@northern.tech>

diff --git a/frontend/tests/e2e_tests/run b/frontend/tests/e2e_tests/run
--- a/frontend/tests/e2e_tests/run
+++ b/frontend/tests/e2e_tests/run
@@ -1,7 +1,7 @@
 #!/bin/bash
 set -e
 
-export SERVER_ROOT=${SERVER_ROOT:-$(git rev-parse --show-toplevel)}
+export SERVER_ROOT=${SERVIER_ROOT:-$(git rev-parse --show-toplevel)}
 export GUI_REPOSITORY=${GUI_REPOSITORY:-${SERVER_ROOT}/frontend}
 export COMPOSE_FILE="${SERVER_ROOT}/docker-compose.yml:${GUI_REPOSITORY}/tests/e2e_tests/docker-compose.e2e-tests.yml"
 
@@ -56,7 +56,6 @@ PASSWORD=mysecretpassword!123
 
 run_tests() {
     docker compose down -v --remove-orphans && docker compose up -d
-    trap cleanup EXIT INT TERM
     declare retries=5
 
     if [[ $ENTERPRISE -eq 1 ]]; then
@@ -99,16 +98,16 @@ run_tests() {
 }
 
 cleanup(){
+    rc=$?
+    logdir=${GUI_REPOSITORY}/logs
+    tmppath=${logdir}/gui_e2e_tests.txt
+    mkdir -p "$logdir"
+    test $rc -ne 0 && \
+      echo "-- tests failed, dumping logs to $tmppath" && \
+      docker compose logs > $tmppath
     [ -z $SKIP_CLEANUP ] && docker compose down -v --remove-orphans || true
 }
 
+trap cleanup EXIT
 parse_args "$@"
 run_tests
-
-if [ -n "$failed" ]; then
-    tmppath=${GUI_REPOSITORY}/logs/gui_e2e_tests.txt
-    echo "-- tests failed, dumping logs to $tmppath"
-    docker compose logs > $tmppath
-fi
-
-exit $failed
