feat: run test_compat separately
Changelog: Title
Ticket: None
Signed-off-by: Peter Grzybowski <peter@northern.tech>

diff --git a/backend/tests/integration/run b/backend/tests/integration/run
--- a/backend/tests/integration/run
+++ b/backend/tests/integration/run
@@ -10,6 +10,9 @@ COMPOSE_FILES_OPEN=" \
         -f $MENDER_SERVER_PATH/backend/tests/docker-compose.yml \
         -f $MENDER_SERVER_PATH/backend/tests/integration/docker/docker-compose.backend-tests.yml \
         "
+COMPOSE_FILES_COMPAT=" \
+        -f $MENDER_SERVER_PATH/backend/tests/integration/docker/docker-compose.backend-tests-compat.yml \
+        "
 COMPOSE_FILES_ENTERPRISE="${COMPOSE_FILES_OPEN} \
         -f $MENDER_SERVER_PATH/backend/tests/integration/docker/docker-compose.backend-tests-enterprise.yml \
         "
@@ -260,6 +263,21 @@ for suite in "${TEST_SUITES[@]}"; do
     fi
 
     prepare_pytest_args
+    export PYTEST_TESTS_INPUTS_PY=`ls /tests/*py | grep -vF test_compat.py`
+    run_tests
+    run_tests_retcode=$?
+    if [ $script_failed -eq 0 ]; then
+        script_failed=$run_tests_retcode
+    fi
+
+    if [ $run_tests_retcode -ne 0 ]; then
+        tmppath=$(TMPDIR=./tests mktemp logs.XXXXXX)
+        echo "-- tests failed, dumping logs to $tmppath"
+        compose_cmd logs > "$tmppath" 2>&1
+    fi
+
+    COMPOSE_FILES="${COMPOSE_FILES} ${COMPOSE_FILES_COMPAT}"
+    export PYTEST_TESTS_INPUTS_PY=/tests/test_compat.py
     run_tests
     run_tests_retcode=$?
     if [ $script_failed -eq 0 ]; then
